version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin_password
      - POSTGRES_DB=cookbook_db
    ports:
      - 5431:5432
    volumes:
      - ./db_volume/:/var/lib/postgresql/data
    networks:
      - app_net

  project:
    build:
      context: .
    restart: always
    stop_signal: SIGKILL
    ports:
      - 8000:8000
    depends_on:
      - db
    entrypoint: >
      sh -c "sleep 5 && alembic upgrade head"
    networks:
      - app_net

networks:
  app_net:
    driver: bridge