"""correct names of models

Revision ID: 0058950a8236
Revises: 4262086f072e
Create Date: 2024-03-21 00:44:43.530778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0058950a8236'
down_revision: Union[str, None] = '4262086f072e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipes_ingredients_table',
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient_table.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe_table.id'], ),
    sa.PrimaryKeyConstraint('recipe_id', 'ingredient_id')
    )
    op.drop_table('recipes_ingridients_table')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipes_ingridients_table',
    sa.Column('recipe_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ingridient_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ingridient_id'], ['ingredient_table.id'], name='recipes_ingridients_table_ingridient_id_fkey'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe_table.id'], name='recipes_ingridients_table_recipe_id_fkey'),
    sa.PrimaryKeyConstraint('recipe_id', 'ingridient_id', name='recipes_ingridients_table_pkey')
    )
    op.drop_table('recipes_ingredients_table')
    # ### end Alembic commands ###
