"""init migration

Revision ID: 4262086f072e
Revises: 
Create Date: 2024-03-20 19:18:53.115229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4262086f072e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredient_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipe_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('cooking_time', sa.Integer(), nullable=False, comment='in minutes'),
    sa.Column('views_qty', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipes_ingridients_table',
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('ingridient_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ingridient_id'], ['ingredient_table.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe_table.id'], ),
    sa.PrimaryKeyConstraint('recipe_id', 'ingridient_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipes_ingridients_table')
    op.drop_table('recipe_table')
    op.drop_table('ingredient_table')
    # ### end Alembic commands ###
